### ISSUE TITLE
Checklist

### ISSUE THREAD

**Issue by menor** [resmio/activities#1]
- [ ] Create the switcher that switchs depending on the activity type
- [ ] Create the templates for:
  - [ ] booking
 - [ ] email
 - [ ] feedback
 - [ ] noshow
 - [ ] google reviews
 - [ ] campaigns
 - [ ] tickets
 - [ ] facility created
 - [ ] no activities
- [ ] Plug an initial component to the main app and check if the 'plug theory' works in practice
